language: node_js
node_js:
- 'node'
install: true
script: true
deploy:
  provider: npm
  email: npm@joestrong.co.uk
  api_key:
    secure: lWk2DKhPP5TS/PMYR5e8+AXEEAx2UGc8RsaXxaDkesnOMBWwmCxxKlMzd9Z00ISpyxeJgUdYJDVCW7OlbCdAU+4HacuskEeMaToSjRLu/P4Dazu8FubE5dpR/jNmR4tiOzn27oiJ38kCiRdhzOFLakkKS8D7gI5YyDT1nQHDWhdlOwJUNAOHxYchEhMruVHMjcjCRfzIWbUlN9xrBoXgRo6c3TRcS04GAGrIoR2rhdRSiztfC9yzC0GBFaauJcQORVt2+oqhv/OPaUhJGg3dspVep/85EGmolhkbm7CDcf3WFnZRpyfC9+r67IZl183I9V8+7XP/zD7raVlSAy9RTWcCv60fbZgAk7b0mAJBkOC6y0lGeqckJffX5MCL3zJMkOMuWmEDr7R4NQER1lZ35QwP51ZLxoxQqghhtQZrR1ihUf3snIjNxf4zP4qThfMeblgPG3qDUGnlFvMzEX9orlAryElqQa2iD+uCNJ+4nCTLpYmIncQRsy2fd+UIrsbXfmRzhF4tUJE9EuviitiJisNiiwMnTpnax362eAcPVHwXp07oKhgdsjcWscUiIQhC2TViiBCyo1xDIZSEBp96c5tjYt6ZhXTU87xABV2lfOxuTeHtdT8IIV+ShcuqgDtYChdegotziJW9Jew7ciWGVR4gFgdb60rjJdyflNfezHg=
  on:
    tags: true
